baseURL = 'https://www.koendejong.net/'
languageCode = 'en'
title = 'Home | Koen de Jong'

assetDir = "static"
enableRobotsTXT = true
defaultContentLanguage = "en"
relativeURLs = true
enableEmoji = true

