baseURL = 'https://www.koendejong.net'
languageCode = 'en'
title = 'Home | Koen de Jong'

assetDir = "static"
enableRobotsTXT = true
defaultContentLanguage = "en"
relativeURLs = true
enableEmoji = true

[params]
	metaDescription = "This is the personal website of Koen de Jong. I am a computer science student at the University of Twente passionate about new technologies and sustainability"

[permalinks]
	pages = "/:slug/"
	posts = "/:slug/"
	categories = "/:slug/"